export default () => {
  const froala_config = {
    placeholderText: "Edit Your Content Here111!",
    height: 300,
    // inlineMode: false,
    pastePlain: true,
    paragraphy: false,
    quickInsertEnabled: false,
    toolbarButtons: [
      //   "undo",
      //   "redo",
      //   "fullscreen",
      //   "|",
      //   "fontSize",
      //   "color",
      //   "bold",
      //   "italic",
      //   "underline",
      //   "inlineClass",
      //   "subscript",
      //   "superscript",
      //   "|",
      //   "paragraphFormat",
      //   "align",
      //   "outdent",
      //   "indent",
      //   "|",
      //   "formatOL",
      //   "formatUL",
      //   "quote",
      //   "-",
      //   "insertLink",
      //   "insertImage",
      //   "insertVideo",
      //   "insertFile",
      //   "insertTable",
      //   "|",
      //   "fontAwesome",
      //   "insertHR",
      //   "selectAll",
      //   "clearFormatting",
      //   "|",
      //   "print",
      //   "getPDF",
      //   "html",
      "bold",
      "italic",
      "underline",
      "strikeThrough",
      "subscript",
      "superscript",
      "|",
      "fontFamily",
      "fontSize",
      "textColor",
      "backgroundColor",
      "inlineClass",
      "inlineStyle",
      "|",
      "paragraphFormat",
      "paragraphStyle",
      "lineHeight",
      "|",
      "align",
      "formatOL",
      "formatUL",
      "outdent",
      "indent",
      "quote",
      "|",
      "insertLink",
      "insertImage",
      "insertVideo",
      "insertFile",
      "insertTable",
      "emoticons",
      "specialCharacters",
      "insertHR",
      "selectAll",
      "|",
      "undo",
      "redo",
      "clearFormatting",
      "fullscreen",
      "html",
    //   "wirisEditor",
    //   "wirisChemistry",
    ],
    // pluginsEnabled: ["wiris"],
    // Change buttons for XS screen.
    // toolbarButtonsXS: [
    //   ["undo", "redo"],
    //   ["bold", "italic", "underline", "subscript", "superscript"],
    // ],
    placeholderText: "",
    attribution: false,
    key: "enter-your-license-key-here",
    disableRightClick: true,
    imageUploadURL: `${import.meta.env.VITE_APP_API_URL}/froala/image`,
    imageAllowedTypes: ["jpeg", "jpg", "png"],
    fileUploadURL: `${import.meta.env.VITE_APP_API_URL}/froala/document`,
    videoUploadURL: `${import.meta.env.VITE_APP_API_URL}/froala/video`,
    // fileUpload: false,
    // imageUpload: false,
    imagePaste: false,
    imagePasteProcess: false,
    imageResize: true,
    crossDomain: true,
  };

  return {
    froala_config,
  };
};
